name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    # 1. Descodifica a tua Keystore permanente na raiz do projeto
    - name: Decode Keystore
      run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release.keystore

    # 2. Dá permissão ao script de compilação do Android
    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew

    # 3. Compila o APK usando o comando nativo do Android
    # Injeta automaticamente os teus 3 segredos para o teu build.gradle.kts ler
    - name: Build Release APK
      env:
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    # 4. Disponibiliza o APK final para download na aba Actions
    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: GameReseller-Release
        path: app/build/outputs/apk/release/app-release.apk
