name: Compilador Android Oficial Otimizado

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Copiar Codigo
      uses: actions/checkout@v4

    - name: Configurar Java Avançado (JDK 17)
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'
        cache: 'gradle'

    - name: Validar ou Criar Gradle Wrapper
      run: |
        if [ ! -f gradle/wrapper/gradle-wrapper.properties ]; then
          echo "Gradle wrapper não encontrado. Gerando um novo..."
          gradle wrapper --gradle-version 8.2
        fi

    - name: Garantir Permissao de Execucao
      run: chmod +x ./gradlew

    - name: Gerar APK Final
      run: ./gradlew assembleDebug --no-daemon

    - name: Guardar APK para Download
      uses: actions/upload-artifact@v4
      with:
        name: AplicacaoPronta
        path: |
          **/build/outputs/apk/debug/*.apk
